providers = ["node"]

[variables]
NODE_VERSION = "20"
NIXPACKS_NODE_VERSION = "20"

[phases.install]
cmds = ["cd frontend && npm install --include=dev", "cd server && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd server && npm start"
